version: '3.8'

services:
  web:
    image: your-laravel-image
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=11013
      - DB_DATABASE=railway
      - DB_USERNAME=root
      - DB_PASSWORD=ftMKHcANburGUFcaNNnVMJqnLQZRBvGo
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:9.0.1
    container_name: mysql
    ports:
      - "11013:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ftMKHcANburGUFcaNNnVMJqnLQZRBvGo
      MYSQL_DATABASE: railway
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
